version: "3.9"
services:
  web:
    build: ./frontend/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./frontend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db

